//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNNJuliusModules.DNNJuliusForm.ServiceReferenceDNNJuliusForm {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="js_DNNJuliusForm", Namespace="http://schemas.datacontract.org/2004/07/Test.Service.Model")]
    [System.SerializableAttribute()]
    public partial class js_DNNJuliusForm : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CelularPropietarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CelularSolicitanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoNiuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartamentoPropietarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartamentoSolicitanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionObraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionPropietarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionSolicitanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentoIdentidadIngenieroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentoIdentidadPropietarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentoIdentidadSolicitanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailPropietarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailSolicitanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> EstratoObraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FactibilidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MatriculaProfesionalIngenieroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MunicipioPropietarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MunicipioSolicitanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreIngenieroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreObraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombrePropietarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreRazonSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> RespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoPropietarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoSolicitanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDocumentoPropietarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDocumentoSolicitanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DNNJuliusModules.DNNJuliusForm.ServiceReferenceDNNJuliusForm.js_DNNJuliusFormArchivo[] js_DNNJuliusFormArchivoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CelularPropietario {
            get {
                return this.CelularPropietarioField;
            }
            set {
                if ((object.ReferenceEquals(this.CelularPropietarioField, value) != true)) {
                    this.CelularPropietarioField = value;
                    this.RaisePropertyChanged("CelularPropietario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CelularSolicitante {
            get {
                return this.CelularSolicitanteField;
            }
            set {
                if ((object.ReferenceEquals(this.CelularSolicitanteField, value) != true)) {
                    this.CelularSolicitanteField = value;
                    this.RaisePropertyChanged("CelularSolicitante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoNiu {
            get {
                return this.CodigoNiuField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoNiuField, value) != true)) {
                    this.CodigoNiuField = value;
                    this.RaisePropertyChanged("CodigoNiu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartamentoPropietario {
            get {
                return this.DepartamentoPropietarioField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentoPropietarioField, value) != true)) {
                    this.DepartamentoPropietarioField = value;
                    this.RaisePropertyChanged("DepartamentoPropietario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartamentoSolicitante {
            get {
                return this.DepartamentoSolicitanteField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentoSolicitanteField, value) != true)) {
                    this.DepartamentoSolicitanteField = value;
                    this.RaisePropertyChanged("DepartamentoSolicitante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DireccionObra {
            get {
                return this.DireccionObraField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionObraField, value) != true)) {
                    this.DireccionObraField = value;
                    this.RaisePropertyChanged("DireccionObra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DireccionPropietario {
            get {
                return this.DireccionPropietarioField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionPropietarioField, value) != true)) {
                    this.DireccionPropietarioField = value;
                    this.RaisePropertyChanged("DireccionPropietario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DireccionSolicitante {
            get {
                return this.DireccionSolicitanteField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionSolicitanteField, value) != true)) {
                    this.DireccionSolicitanteField = value;
                    this.RaisePropertyChanged("DireccionSolicitante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentoIdentidadIngeniero {
            get {
                return this.DocumentoIdentidadIngenieroField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentoIdentidadIngenieroField, value) != true)) {
                    this.DocumentoIdentidadIngenieroField = value;
                    this.RaisePropertyChanged("DocumentoIdentidadIngeniero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentoIdentidadPropietario {
            get {
                return this.DocumentoIdentidadPropietarioField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentoIdentidadPropietarioField, value) != true)) {
                    this.DocumentoIdentidadPropietarioField = value;
                    this.RaisePropertyChanged("DocumentoIdentidadPropietario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentoIdentidadSolicitante {
            get {
                return this.DocumentoIdentidadSolicitanteField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentoIdentidadSolicitanteField, value) != true)) {
                    this.DocumentoIdentidadSolicitanteField = value;
                    this.RaisePropertyChanged("DocumentoIdentidadSolicitante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailPropietario {
            get {
                return this.EmailPropietarioField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailPropietarioField, value) != true)) {
                    this.EmailPropietarioField = value;
                    this.RaisePropertyChanged("EmailPropietario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailSolicitante {
            get {
                return this.EmailSolicitanteField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailSolicitanteField, value) != true)) {
                    this.EmailSolicitanteField = value;
                    this.RaisePropertyChanged("EmailSolicitante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EstratoObra {
            get {
                return this.EstratoObraField;
            }
            set {
                if ((this.EstratoObraField.Equals(value) != true)) {
                    this.EstratoObraField = value;
                    this.RaisePropertyChanged("EstratoObra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Factibilidad {
            get {
                return this.FactibilidadField;
            }
            set {
                if ((object.ReferenceEquals(this.FactibilidadField, value) != true)) {
                    this.FactibilidadField = value;
                    this.RaisePropertyChanged("Factibilidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MatriculaProfesionalIngeniero {
            get {
                return this.MatriculaProfesionalIngenieroField;
            }
            set {
                if ((object.ReferenceEquals(this.MatriculaProfesionalIngenieroField, value) != true)) {
                    this.MatriculaProfesionalIngenieroField = value;
                    this.RaisePropertyChanged("MatriculaProfesionalIngeniero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MunicipioPropietario {
            get {
                return this.MunicipioPropietarioField;
            }
            set {
                if ((object.ReferenceEquals(this.MunicipioPropietarioField, value) != true)) {
                    this.MunicipioPropietarioField = value;
                    this.RaisePropertyChanged("MunicipioPropietario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MunicipioSolicitante {
            get {
                return this.MunicipioSolicitanteField;
            }
            set {
                if ((object.ReferenceEquals(this.MunicipioSolicitanteField, value) != true)) {
                    this.MunicipioSolicitanteField = value;
                    this.RaisePropertyChanged("MunicipioSolicitante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreIngeniero {
            get {
                return this.NombreIngenieroField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreIngenieroField, value) != true)) {
                    this.NombreIngenieroField = value;
                    this.RaisePropertyChanged("NombreIngeniero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreObra {
            get {
                return this.NombreObraField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreObraField, value) != true)) {
                    this.NombreObraField = value;
                    this.RaisePropertyChanged("NombreObra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombrePropietario {
            get {
                return this.NombrePropietarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NombrePropietarioField, value) != true)) {
                    this.NombrePropietarioField = value;
                    this.RaisePropertyChanged("NombrePropietario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreRazonSocial {
            get {
                return this.NombreRazonSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreRazonSocialField, value) != true)) {
                    this.NombreRazonSocialField = value;
                    this.RaisePropertyChanged("NombreRazonSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observaciones {
            get {
                return this.ObservacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionesField, value) != true)) {
                    this.ObservacionesField = value;
                    this.RaisePropertyChanged("Observaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Respuesta {
            get {
                return this.RespuestaField;
            }
            set {
                if ((this.RespuestaField.Equals(value) != true)) {
                    this.RespuestaField = value;
                    this.RaisePropertyChanged("Respuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelefonoPropietario {
            get {
                return this.TelefonoPropietarioField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoPropietarioField, value) != true)) {
                    this.TelefonoPropietarioField = value;
                    this.RaisePropertyChanged("TelefonoPropietario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelefonoSolicitante {
            get {
                return this.TelefonoSolicitanteField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoSolicitanteField, value) != true)) {
                    this.TelefonoSolicitanteField = value;
                    this.RaisePropertyChanged("TelefonoSolicitante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDocumentoPropietario {
            get {
                return this.TipoDocumentoPropietarioField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDocumentoPropietarioField, value) != true)) {
                    this.TipoDocumentoPropietarioField = value;
                    this.RaisePropertyChanged("TipoDocumentoPropietario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDocumentoSolicitante {
            get {
                return this.TipoDocumentoSolicitanteField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDocumentoSolicitanteField, value) != true)) {
                    this.TipoDocumentoSolicitanteField = value;
                    this.RaisePropertyChanged("TipoDocumentoSolicitante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DNNJuliusModules.DNNJuliusForm.ServiceReferenceDNNJuliusForm.js_DNNJuliusFormArchivo[] js_DNNJuliusFormArchivo {
            get {
                return this.js_DNNJuliusFormArchivoField;
            }
            set {
                if ((object.ReferenceEquals(this.js_DNNJuliusFormArchivoField, value) != true)) {
                    this.js_DNNJuliusFormArchivoField = value;
                    this.RaisePropertyChanged("js_DNNJuliusFormArchivo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="js_DNNJuliusFormArchivo", Namespace="http://schemas.datacontract.org/2004/07/Test.Service.Model")]
    [System.SerializableAttribute()]
    public partial class js_DNNJuliusFormArchivo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> DNNJuliusFormIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FuenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RutaFisicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DNNJuliusModules.DNNJuliusForm.ServiceReferenceDNNJuliusForm.js_DNNJuliusForm js_DNNJuliusFormField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> DNNJuliusFormId {
            get {
                return this.DNNJuliusFormIdField;
            }
            set {
                if ((this.DNNJuliusFormIdField.Equals(value) != true)) {
                    this.DNNJuliusFormIdField = value;
                    this.RaisePropertyChanged("DNNJuliusFormId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fuente {
            get {
                return this.FuenteField;
            }
            set {
                if ((object.ReferenceEquals(this.FuenteField, value) != true)) {
                    this.FuenteField = value;
                    this.RaisePropertyChanged("Fuente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RutaFisica {
            get {
                return this.RutaFisicaField;
            }
            set {
                if ((object.ReferenceEquals(this.RutaFisicaField, value) != true)) {
                    this.RutaFisicaField = value;
                    this.RaisePropertyChanged("RutaFisica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DNNJuliusModules.DNNJuliusForm.ServiceReferenceDNNJuliusForm.js_DNNJuliusForm js_DNNJuliusForm {
            get {
                return this.js_DNNJuliusFormField;
            }
            set {
                if ((object.ReferenceEquals(this.js_DNNJuliusFormField, value) != true)) {
                    this.js_DNNJuliusFormField = value;
                    this.RaisePropertyChanged("js_DNNJuliusForm");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceDNNJuliusForm.IServiceTest")]
    public interface IServiceTest {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTest/GuardarDNNJuliusForm", ReplyAction="http://tempuri.org/IServiceTest/GuardarDNNJuliusFormResponse")]
        DNNJuliusModules.DNNJuliusForm.ServiceReferenceDNNJuliusForm.js_DNNJuliusForm GuardarDNNJuliusForm(DNNJuliusModules.DNNJuliusForm.ServiceReferenceDNNJuliusForm.js_DNNJuliusForm oForm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTest/GuardarDNNJuliusForm", ReplyAction="http://tempuri.org/IServiceTest/GuardarDNNJuliusFormResponse")]
        System.Threading.Tasks.Task<DNNJuliusModules.DNNJuliusForm.ServiceReferenceDNNJuliusForm.js_DNNJuliusForm> GuardarDNNJuliusFormAsync(DNNJuliusModules.DNNJuliusForm.ServiceReferenceDNNJuliusForm.js_DNNJuliusForm oForm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTest/GuardarDNNJuliusFormArchivo", ReplyAction="http://tempuri.org/IServiceTest/GuardarDNNJuliusFormArchivoResponse")]
        DNNJuliusModules.DNNJuliusForm.ServiceReferenceDNNJuliusForm.js_DNNJuliusFormArchivo GuardarDNNJuliusFormArchivo(DNNJuliusModules.DNNJuliusForm.ServiceReferenceDNNJuliusForm.js_DNNJuliusFormArchivo oFormFile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTest/GuardarDNNJuliusFormArchivo", ReplyAction="http://tempuri.org/IServiceTest/GuardarDNNJuliusFormArchivoResponse")]
        System.Threading.Tasks.Task<DNNJuliusModules.DNNJuliusForm.ServiceReferenceDNNJuliusForm.js_DNNJuliusFormArchivo> GuardarDNNJuliusFormArchivoAsync(DNNJuliusModules.DNNJuliusForm.ServiceReferenceDNNJuliusForm.js_DNNJuliusFormArchivo oFormFile);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceTestChannel : DNNJuliusModules.DNNJuliusForm.ServiceReferenceDNNJuliusForm.IServiceTest, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceTestClient : System.ServiceModel.ClientBase<DNNJuliusModules.DNNJuliusForm.ServiceReferenceDNNJuliusForm.IServiceTest>, DNNJuliusModules.DNNJuliusForm.ServiceReferenceDNNJuliusForm.IServiceTest {
        
        public ServiceTestClient() {
        }
        
        public ServiceTestClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceTestClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceTestClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceTestClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DNNJuliusModules.DNNJuliusForm.ServiceReferenceDNNJuliusForm.js_DNNJuliusForm GuardarDNNJuliusForm(DNNJuliusModules.DNNJuliusForm.ServiceReferenceDNNJuliusForm.js_DNNJuliusForm oForm) {
            return base.Channel.GuardarDNNJuliusForm(oForm);
        }
        
        public System.Threading.Tasks.Task<DNNJuliusModules.DNNJuliusForm.ServiceReferenceDNNJuliusForm.js_DNNJuliusForm> GuardarDNNJuliusFormAsync(DNNJuliusModules.DNNJuliusForm.ServiceReferenceDNNJuliusForm.js_DNNJuliusForm oForm) {
            return base.Channel.GuardarDNNJuliusFormAsync(oForm);
        }
        
        public DNNJuliusModules.DNNJuliusForm.ServiceReferenceDNNJuliusForm.js_DNNJuliusFormArchivo GuardarDNNJuliusFormArchivo(DNNJuliusModules.DNNJuliusForm.ServiceReferenceDNNJuliusForm.js_DNNJuliusFormArchivo oFormFile) {
            return base.Channel.GuardarDNNJuliusFormArchivo(oFormFile);
        }
        
        public System.Threading.Tasks.Task<DNNJuliusModules.DNNJuliusForm.ServiceReferenceDNNJuliusForm.js_DNNJuliusFormArchivo> GuardarDNNJuliusFormArchivoAsync(DNNJuliusModules.DNNJuliusForm.ServiceReferenceDNNJuliusForm.js_DNNJuliusFormArchivo oFormFile) {
            return base.Channel.GuardarDNNJuliusFormArchivoAsync(oFormFile);
        }
    }
}
